import { defineSlotRecipe } from "@pandacss/dev"

export const commandPalette = defineSlotRecipe({
	className: "command-palette",
	slots: [
		"backdrop",
		"panel",
		"inputRow",
		"input",
		"results",
		"sectionLabel",
		"item",
		"itemSwatch",
		"itemLabel",
		"itemDesc",
		"empty",
		"footer",
		"footerHint",
		"footerKey",
	],

	base: {
		backdrop: {
			position: "fixed",
			inset: "0",
			zIndex: "modal",
			bg: "rgba(44, 42, 39, 0.28)",
			backdropFilter: "blur(3px)",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			animation: "paletteFadeIn 0.15s {easings.inOut} both",
		},
		panel: {
			width: "560px",
			maxWidth: "calc(100vw - 40px)",
			bg: "white",
			borderWidth: "1",
			borderStyle: "solid",
			borderColor: "border.subtle",
			borderRadius: "xl",
			boxShadow: "lg",
			overflow: "hidden",
			animation: "paletteSlideDown 0.22s {easings.spring} both",
		},
		inputRow: {
			display: "flex",
			alignItems: "center",
			gap: "2.5",
			px: "3.5",
			h: "12",
			borderBottomWidth: "1",
			borderBottomStyle: "solid",
			borderBottomColor: "border.subtle",
			// icon slot
			"& [data-slot=icon]": {
				color: "fg.subtle",
				flexShrink: "0",
			},
		},
		input: {
			flex: "1",
			border: "none",
			outline: "none",
			background: "transparent",
			fontSize: "md",
			color: "fg.default",
			fontFamily: "sans",
			_placeholder: {
				color: "fg.subtle",
			},
		},
		results: {
			maxHeight: "360px",
			overflowY: "auto",
			py: "1",
			scrollbarWidth: "thin",
			scrollbarColor: "token(colors.stone.300) transparent",
		},
		sectionLabel: {
			fontSize: "xxs",
			fontWeight: "bold",
			letterSpacing: "wider",
			textTransform: "uppercase",
			color: "fg.subtle",
			px: "3.5",
			pt: "2",
			pb: "1",
		},
		item: {
			display: "flex",
			alignItems: "center",
			gap: "2.5",
			px: "2.5",
			py: "2",
			mx: "1",
			borderRadius: "md",
			cursor: "pointer",
			border: "none",
			background: "transparent",
			width: "calc(100% - 8px)",
			textAlign: "left",
			fontFamily: "sans",
			transition: "colors 0.1s ease",
			_hover: {
				bg: "brand.subtle",
			},
			"&[data-active]": {
				bg: "brand.subtle",
			},
			"&[data-active] [data-slot=label]": {
				color: "brand.emphasis",
			},
		},
		itemSwatch: {
			width: "10px",
			height: "10px",
			borderRadius: "2px",
			flexShrink: "0",
		},
		itemLabel: {
			fontSize: "sm",
			fontWeight: "medium",
			color: "fg.default",
			flex: "1",
		},
		itemDesc: {
			fontSize: "xxs",
			color: "fg.subtle",
			whiteSpace: "nowrap",
		},
		empty: {
			py: "8",
			px: "3.5",
			textAlign: "center",
			fontSize: "sm",
			color: "fg.subtle",
		},
		footer: {
			display: "flex",
			alignItems: "center",
			gap: "3.5",
			px: "3.5",
			py: "1.5",
			borderTopWidth: "1",
			borderTopStyle: "solid",
			borderTopColor: "border.subtle",
		},
		footerHint: {
			display: "flex",
			alignItems: "center",
			gap: "1",
			fontSize: "xxs",
			color: "fg.subtle",
		},
		footerKey: {
			bg: "bg.muted",
			borderWidth: "1",
			borderStyle: "solid",
			borderColor: "border.default",
			borderRadius: "sm",
			px: "1",
			py: "0.5",
			fontSize: "xxs",
			fontWeight: "semibold",
			color: "fg.muted",
			fontFamily: "sans",
			boxShadow: "0 1px 0 token(colors.stone.300)",
		},
	},
})
