query GetProposal($slug: String!) {
	proposalBySlug(slug: $slug) {
		... on NotFoundError {
			message
		}
		... on Proposal {
			id
			fabricId
			isLikedByMe
			description
			publishedAt
			slug
			commentCount
			numPhotos
			creator {
				id
				name
				username
				profilePictureUrl
				isFollowedByMe
			}
			categories
			existingConditionPhotos {
				id
				group
				url
				caption
			}
			inspirationPhotos {
				id
				group
				url
				caption
			}
			likeCount
			snapshotCenter {
				lat
				lng
			}
			snapshotElements
			snapshotLocationCity
			snapshotLocationRegion
			snapshotLocationRegionAbbr
			snapshotMapStyle
			snapshotIsIn3DMode
			snapshotThumbnail
			snapshotZoom
			title
			viewCount
		}
	}
}
