query ExploreProposals(
	$categories: [ProposalCategory!]
	$limit: Int
	$offset: Int
	$search: String
	$sortBy: ExploreSortBy
	$nearLat: Float
	$nearLng: Float
	$radiusMiles: Float
) {
	exploreProposals(
		categories: $categories
		limit: $limit
		offset: $offset
		search: $search
		sortBy: $sortBy
		nearLat: $nearLat
		nearLng: $nearLng
		radiusMiles: $radiusMiles
	) {
		hasMore
		total
		proposals {
			...ProposalCard
		}
	}
}

fragment ProposalCard on Proposal {
	id
	title
	viewCount
	commentCount
	slug
	likeCount
	isLikedByMe
	snapshotLocationCity
	snapshotLocationRegion
	snapshotLocationRegionAbbr
	snapshotThumbnail
	publishedAt
	creator {
		id
		name
		username
		profilePictureUrl
	}
	categories
}
