query MyProposals(
	$offset: Int
	$limit: Int
	$status: ProposalStatusFilter
	$categories: [ProposalCategory!]
	$search: String
) {
	myProposals(
		offset: $offset
		limit: $limit
		status: $status
		categories: $categories
		search: $search
	) {
		... on UnauthorizedError {
			message
		}
		... on MyProposalsPayload {
			total
			hasMore
			proposals {
				...ProposalRow
			}
		}
	}
}

fragment ProposalRow on Proposal {
	id
	fabricId
	title
	updatedAt
	viewCount
	slug
	likeCount
	isPublished
	snapshotLocationCity
	snapshotLocationRegion
	snapshotThumbnail
}
