/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as FabricNewRouteImport } from './routes/fabric/new'
import { Route as DashboardProposalsRouteImport } from './routes/dashboard/proposals'
import { Route as DashboardFabricsRouteImport } from './routes/dashboard/fabrics'
import { Route as FabricIdRouteRouteImport } from './routes/fabric/$id/route'
import { Route as MarketingAuthRouteRouteImport } from './routes/_marketing/_auth/route'
import { Route as FabricIdIndexRouteImport } from './routes/fabric/$id/index'
import { Route as FabricIdPublishRouteImport } from './routes/fabric/$id/publish'
import { Route as MarketingAuthRegisterRouteImport } from './routes/_marketing/_auth/register'
import { Route as MarketingAuthLoginRouteImport } from './routes/_marketing/_auth/login'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const FabricNewRoute = FabricNewRouteImport.update({
  id: '/fabric/new',
  path: '/fabric/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProposalsRoute = DashboardProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFabricsRoute = DashboardFabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const FabricIdRouteRoute = FabricIdRouteRouteImport.update({
  id: '/fabric/$id',
  path: '/fabric/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAuthRouteRoute = MarketingAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const FabricIdIndexRoute = FabricIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FabricIdRouteRoute,
} as any)
const FabricIdPublishRoute = FabricIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => FabricIdRouteRoute,
} as any)
const MarketingAuthRegisterRoute = MarketingAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MarketingAuthRouteRoute,
} as any)
const MarketingAuthLoginRoute = MarketingAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MarketingAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/fabric/$id': typeof FabricIdRouteRouteWithChildren
  '/dashboard/fabrics': typeof DashboardFabricsRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/fabric/new': typeof FabricNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login': typeof MarketingAuthLoginRoute
  '/register': typeof MarketingAuthRegisterRoute
  '/fabric/$id/publish': typeof FabricIdPublishRoute
  '/fabric/$id/': typeof FabricIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/dashboard/fabrics': typeof DashboardFabricsRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/fabric/new': typeof FabricNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof MarketingAuthLoginRoute
  '/register': typeof MarketingAuthRegisterRoute
  '/fabric/$id/publish': typeof FabricIdPublishRoute
  '/fabric/$id': typeof FabricIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_marketing/_auth': typeof MarketingAuthRouteRouteWithChildren
  '/fabric/$id': typeof FabricIdRouteRouteWithChildren
  '/dashboard/fabrics': typeof DashboardFabricsRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/fabric/new': typeof FabricNewRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_marketing/_auth/login': typeof MarketingAuthLoginRoute
  '/_marketing/_auth/register': typeof MarketingAuthRegisterRoute
  '/fabric/$id/publish': typeof FabricIdPublishRoute
  '/fabric/$id/': typeof FabricIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fabric/$id'
    | '/dashboard/fabrics'
    | '/dashboard/proposals'
    | '/fabric/new'
    | '/dashboard/'
    | '/login'
    | '/register'
    | '/fabric/$id/publish'
    | '/fabric/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/fabrics'
    | '/dashboard/proposals'
    | '/fabric/new'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/fabric/$id/publish'
    | '/fabric/$id'
  id:
    | '__root__'
    | '/_marketing'
    | '/dashboard'
    | '/_marketing/_auth'
    | '/fabric/$id'
    | '/dashboard/fabrics'
    | '/dashboard/proposals'
    | '/fabric/new'
    | '/_marketing/'
    | '/dashboard/'
    | '/_marketing/_auth/login'
    | '/_marketing/_auth/register'
    | '/fabric/$id/publish'
    | '/fabric/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  FabricIdRouteRoute: typeof FabricIdRouteRouteWithChildren
  FabricNewRoute: typeof FabricNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/fabric/new': {
      id: '/fabric/new'
      path: '/fabric/new'
      fullPath: '/fabric/new'
      preLoaderRoute: typeof FabricNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/proposals': {
      id: '/dashboard/proposals'
      path: '/proposals'
      fullPath: '/dashboard/proposals'
      preLoaderRoute: typeof DashboardProposalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/fabrics': {
      id: '/dashboard/fabrics'
      path: '/fabrics'
      fullPath: '/dashboard/fabrics'
      preLoaderRoute: typeof DashboardFabricsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/fabric/$id': {
      id: '/fabric/$id'
      path: '/fabric/$id'
      fullPath: '/fabric/$id'
      preLoaderRoute: typeof FabricIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/_auth': {
      id: '/_marketing/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingAuthRouteRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/fabric/$id/': {
      id: '/fabric/$id/'
      path: '/'
      fullPath: '/fabric/$id/'
      preLoaderRoute: typeof FabricIdIndexRouteImport
      parentRoute: typeof FabricIdRouteRoute
    }
    '/fabric/$id/publish': {
      id: '/fabric/$id/publish'
      path: '/publish'
      fullPath: '/fabric/$id/publish'
      preLoaderRoute: typeof FabricIdPublishRouteImport
      parentRoute: typeof FabricIdRouteRoute
    }
    '/_marketing/_auth/register': {
      id: '/_marketing/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MarketingAuthRegisterRouteImport
      parentRoute: typeof MarketingAuthRouteRoute
    }
    '/_marketing/_auth/login': {
      id: '/_marketing/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MarketingAuthLoginRouteImport
      parentRoute: typeof MarketingAuthRouteRoute
    }
  }
}

interface MarketingAuthRouteRouteChildren {
  MarketingAuthLoginRoute: typeof MarketingAuthLoginRoute
  MarketingAuthRegisterRoute: typeof MarketingAuthRegisterRoute
}

const MarketingAuthRouteRouteChildren: MarketingAuthRouteRouteChildren = {
  MarketingAuthLoginRoute: MarketingAuthLoginRoute,
  MarketingAuthRegisterRoute: MarketingAuthRegisterRoute,
}

const MarketingAuthRouteRouteWithChildren =
  MarketingAuthRouteRoute._addFileChildren(MarketingAuthRouteRouteChildren)

interface MarketingRouteRouteChildren {
  MarketingAuthRouteRoute: typeof MarketingAuthRouteRouteWithChildren
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingAuthRouteRoute: MarketingAuthRouteRouteWithChildren,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardFabricsRoute: typeof DashboardFabricsRoute
  DashboardProposalsRoute: typeof DashboardProposalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardFabricsRoute: DashboardFabricsRoute,
  DashboardProposalsRoute: DashboardProposalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface FabricIdRouteRouteChildren {
  FabricIdPublishRoute: typeof FabricIdPublishRoute
  FabricIdIndexRoute: typeof FabricIdIndexRoute
}

const FabricIdRouteRouteChildren: FabricIdRouteRouteChildren = {
  FabricIdPublishRoute: FabricIdPublishRoute,
  FabricIdIndexRoute: FabricIdIndexRoute,
}

const FabricIdRouteRouteWithChildren = FabricIdRouteRoute._addFileChildren(
  FabricIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  FabricIdRouteRoute: FabricIdRouteRouteWithChildren,
  FabricNewRoute: FabricNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
